<?php
// $Id: feeds_querypath_parser.module,v 1.1.2.1.2.1 2011/02/05 21:34:01 twistor Exp $

/**
 * Implements hook_feeds_plugins().
 */
function feeds_querypath_parser_feeds_plugins() {
  $info = array();
   $info['FeedsQueryPathParser'] = array(
    'name'        => t('QueryPath parser'),
    'description' => t('Parse XML or HTML using QueryPath.'),
    'handler'     => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsQueryPathParser',
      'file'   => 'FeedsQueryPathParser.inc',
      'path'   => drupal_get_path('module', 'feeds_querypath_parser'),
    ),
  );
  return $info;
}

/**
 * Implementats hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function feeds_querypath_parser_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
